# Generated by Django 5.0.6 on 2024-07-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_payment_payment_time_payment_payment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
